import type {
  BrandAsset,
  BrandColor,
  BrandFont,
  BrandGuideline,
  BrandMessageFramework,
  BrandProfile,
} from "./brand-types";

export const brandProfiles: BrandProfile[] = [
  {
    id: "brand_gozbebekleri",
    key: "gozbebekleri",
    name: "Gözbebekleri Derneği",
    description: "Main operating charity identity for the current dashboard.",
    mission: "Deliver trusted relief campaigns with clear donor proof and practical field updates.",
    vision: "A donor journey where every contribution is simple to give, easy to trust, and visibly connected to impact.",
    contentVoice: "Warm, reliable, direct, relief-focused, and proof-led.",
    messagePhilosophy: "Keep the donor close to the field without exaggeration; show proof, receipt, and next action clearly.",
    primaryLocale: "tr",
    supportedLocales: ["tr", "ar", "en"],
    website: "gozbebekleri.org",
    isActive: true,
    status: "FOUNDATION",
    verificationNote: "Active dashboard profile; official logo/file assets still need final upload verification.",
  },
  {
    id: "brand_minber_aksa",
    key: "minber_aksa",
    name: "Minber-i Aksa Derneği",
    description: "Al-Quds, Al-Aqsa, Gaza, zakat, waqf, and recurring giving identity.",
    mission: "Support Al-Quds, Al-Aqsa, Gaza, zakat, waqf, and field-backed giving with a premium multilingual donor experience.",
    vision: "Make donor impact visible in Al-Quds, Al-Aqsa, and Gaza through official projects, reports, receipts, and certificates.",
    contentVoice: "Modern Islamic, Al-Quds focused, calm, trustworthy, urgent only when evidence supports it.",
    messagePhilosophy: "Use official language, visible proof, zakat/waqf clarity, and donor dignity in every message.",
    primaryLocale: "tr",
    supportedLocales: ["ar", "en", "fr", "tr", "id", "pt", "es", "de"],
    website: "minberiaksa.org",
    isActive: false,
    status: "FOUNDATION",
    verificationNote: "Use official website content/media only when building public Minber-i Aksa pages.",
  },
  {
    id: "brand_burak",
    key: "burak",
    name: "Burak Derneği",
    description: "Secondary charity identity with a softer Turkish campaign tone.",
    mission: "Provide clear Turkish donor journeys for relief and qurban campaigns.",
    vision: "A calm, trusted donation experience backed by after-donation proof and simple updates.",
    contentVoice: "Soft, trustworthy, Turkish charity tone, clear and grounded.",
    messagePhilosophy: "Keep donation copy practical, local, and proof-oriented without overpromising.",
    primaryLocale: "tr",
    supportedLocales: ["tr"],
    website: "burakdernegi.org",
    isActive: false,
    status: "FOUNDATION",
    verificationNote: "Contact and social data require official verification before production public use.",
  },
];

export const brandAssets: BrandAsset[] = [
  {
    id: "asset_goz_primary_logo",
    profileId: "brand_gozbebekleri",
    title: "Primary logo",
    type: "LOGO",
    format: "SVG",
    fileUrl: null,
    previewUrl: null,
    usage: "Main dashboard, donation receipts, and official campaign headers.",
    locale: "all",
    notes: "to be verified: upload approved vector/logo file.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_goz_receipt_template",
    profileId: "brand_gozbebekleri",
    title: "Donation receipt template",
    type: "CERTIFICATE",
    format: "PDF",
    fileUrl: null,
    previewUrl: null,
    usage: "Receipt and thank-you proof journey.",
    locale: "tr",
    notes: "to be verified: connect to real certificate template asset.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_minber_waqf_certificate",
    profileId: "brand_minber_aksa",
    title: "Waqf certificate direction",
    type: "CERTIFICATE",
    format: "PDF",
    fileUrl: null,
    previewUrl: null,
    usage: "Al-Quds waqf donation certificate preview and post-donation download.",
    locale: "all",
    notes: "to be verified: use official Minber-i Aksa certificate design when available.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_minber_pattern_edge",
    profileId: "brand_minber_aksa",
    title: "Subtle geometric certificate edge",
    type: "TEMPLATE",
    format: "FIGMA",
    fileUrl: null,
    previewUrl: null,
    usage: "Soft Islamic accent only on certificate edges or section dividers, never over text or forms.",
    locale: "all",
    notes: "to be verified: design source pending.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_burak_intro",
    profileId: "brand_burak",
    title: "Video intro/outro placeholder",
    type: "VIDEO_INTRO",
    format: "VIDEO",
    fileUrl: null,
    previewUrl: null,
    usage: "Qurban and field proof videos after official approval.",
    locale: "tr",
    notes: "to be verified: upload final motion asset.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
];

export const brandColors: BrandColor[] = [
  { id: "color_goz_blue", profileId: "brand_gozbebekleri", name: "Trust Blue", hex: "#025EB8", rgb: "2, 94, 184", usage: "PRIMARY", description: "Primary identity and dashboard accent color.", order: 1 },
  { id: "color_goz_navy", profileId: "brand_gozbebekleri", name: "Deep Navy", hex: "#10212B", rgb: "16, 33, 43", usage: "TEXT", description: "Headers, trust panels, and serious dashboard surfaces.", order: 2 },
  { id: "color_goz_ivory", profileId: "brand_gozbebekleri", name: "Warm Surface", hex: "#FFFDF8", rgb: "255, 253, 248", usage: "BACKGROUND", description: "Soft background for donor-facing brand pages.", order: 3 },
  { id: "color_minber_trust_navy", profileId: "brand_minber_aksa", name: "Trust Navy", hex: "#10212B", rgb: "16, 33, 43", usage: "PRIMARY", description: "Primary Minber-i Aksa trust color.", order: 1 },
  { id: "color_minber_deep_navy", profileId: "brand_minber_aksa", name: "Deep Navy", hex: "#132C38", rgb: "19, 44, 56", usage: "TEXT", description: "Headers and high-trust panels.", order: 2 },
  { id: "color_minber_gold", profileId: "brand_minber_aksa", name: "Aqsa Gold", hex: "#D39A27", rgb: "211, 154, 39", usage: "ACCENT", description: "Waqf, certificate, and Al-Aqsa accents.", order: 3 },
  { id: "color_minber_red", profileId: "brand_minber_aksa", name: "Minber Red", hex: "#A93428", rgb: "169, 52, 40", usage: "CTA", description: "Urgent donation actions and Gaza emphasis.", order: 4 },
  { id: "color_minber_green", profileId: "brand_minber_aksa", name: "Zakat Green", hex: "#1F7A4D", rgb: "31, 122, 77", usage: "STATUS", description: "Zakat eligibility and verified giving cues.", order: 5 },
  { id: "color_minber_ivory", profileId: "brand_minber_aksa", name: "Light Ivory", hex: "#FFFDF8", rgb: "255, 253, 248", usage: "BACKGROUND", description: "Primary warm page background.", order: 6 },
  { id: "color_minber_sand", profileId: "brand_minber_aksa", name: "Soft Sand", hex: "#F7F2EA", rgb: "247, 242, 234", usage: "BACKGROUND", description: "Secondary section background.", order: 7 },
  { id: "color_minber_muted", profileId: "brand_minber_aksa", name: "Muted Text", hex: "#52616B", rgb: "82, 97, 107", usage: "TEXT", description: "Long-form supporting text.", order: 8 },
  { id: "color_burak_teal", profileId: "brand_burak", name: "Burak Teal", hex: "#025E73", rgb: "2, 94, 115", usage: "PRIMARY", description: "Primary Burak identity color.", order: 1 },
  { id: "color_burak_soft", profileId: "brand_burak", name: "Soft Blue", hex: "#EAF6FA", rgb: "234, 246, 250", usage: "BACKGROUND", description: "Soft campaign background.", order: 2 },
];

export const brandFonts: BrandFont[] = [
  { id: "font_goz_ui", profileId: "brand_gozbebekleri", name: "System UI", usage: "Dashboard interface", fallback: "Inter, Arial, sans-serif", source: "system", notes: "Stable for internal dashboard screens." },
  { id: "font_minber_ar", profileId: "brand_minber_aksa", name: "Noto Kufi Arabic", usage: "Arabic headings", fallback: "Tajawal, Arial, sans-serif", source: "Google Fonts", notes: "to be verified against final public website typography." },
  { id: "font_minber_latin", profileId: "brand_minber_aksa", name: "Poppins", usage: "Latin headings and CTAs", fallback: "Inter, Arial, sans-serif", source: "Google Fonts", notes: "Works for English, Turkish, French, Portuguese, Spanish, German, Indonesian." },
  { id: "font_burak_ui", profileId: "brand_burak", name: "Inter", usage: "Turkish campaign UI", fallback: "Arial, sans-serif", source: "system/google", notes: "to be verified with final Burak design system." },
];

export const brandGuidelines: BrandGuideline[] = [
  {
    id: "guide_goz_proof",
    profileId: "brand_gozbebekleri",
    section: "proof",
    title: "Proof before pressure",
    body: "Campaign copy should show field updates, receipts, or operational proof before asking for a higher amount.",
    examples: ["Receipt available after donation", "Field update will be shared after distribution"],
    order: 1,
  },
  {
    id: "guide_goz_dignity",
    profileId: "brand_gozbebekleri",
    section: "donor-dignity",
    title: "Protect beneficiary dignity",
    body: "Avoid language that humiliates people receiving aid. Show need with respect and a clear next action.",
    examples: ["Support a family with a verified food parcel", "Do not use pity-heavy wording"],
    order: 2,
  },
  {
    id: "guide_minber_alquds",
    profileId: "brand_minber_aksa",
    section: "copy",
    title: "Use Al-Quds in English",
    body: "Use Al-Quds in English donor copy. Use Jerusalem only when a legal, address, or official quoted source requires it.",
    examples: ["Make your impact visible in Al-Quds, Al-Aqsa and Gaza", "Avoid generic city wording"],
    order: 1,
  },
  {
    id: "guide_minber_zakat",
    profileId: "brand_minber_aksa",
    section: "proof",
    title: "Zakat clarity",
    body: "Zakat copy must explain eligibility, separated receipt handling, scholar note status, and proof availability.",
    examples: ["Zakat-eligible fund", "Separated zakat receipt", "Scholar note to be verified"],
    order: 2,
  },
  {
    id: "guide_minber_waqf",
    profileId: "brand_minber_aksa",
    section: "voice",
    title: "Waqf feels lasting",
    body: "Waqf messaging should feel premium, permanent, and certificate-based without decorative clutter.",
    examples: ["Dedicate this waqf share by name", "Certificate preview before checkout"],
    order: 3,
  },
  {
    id: "guide_global_ai",
    profileId: "brand_gozbebekleri",
    section: "cta",
    title: "AI outputs are drafts",
    body: "AI may suggest copy, translations, and guardrail checks, but cannot publish, send messages, change budgets, or approve assets.",
    examples: ["Draft only", "Needs human approval"],
    order: 3,
  },
];

export const brandMessageFrameworks: BrandMessageFramework[] = [
  {
    id: "framework_goz_friday",
    profileId: "brand_gozbebekleri",
    name: "Friday giving",
    type: "FRIDAY",
    locale: "tr",
    structure: ["Short blessing", "Verified need", "Donation action", "Receipt/proof cue"],
    sampleText: "Cuma iyiliğinizi bugün güvenli bağışla ulaştırın. Bağış sonrası makbuz ve güncelleme paylaşılır.",
    doList: ["Keep it short", "Mention receipt", "Use one CTA"],
    dontList: ["Do not promise exact outcomes without proof", "Do not pressure with guilt"],
  },
  {
    id: "framework_goz_thank_you",
    profileId: "brand_gozbebekleri",
    name: "Thank you",
    type: "THANK_YOU",
    locale: "tr",
    structure: ["Gratitude", "Donation summary", "Receipt note", "Next update"],
    sampleText: "Bağışınız için teşekkür ederiz. Makbuzunuz hazır olduğunda paylaşılacak, saha güncellemesi ayrıca iletilecektir.",
    doList: ["Confirm trust", "Explain next proof step"],
    dontList: ["Do not add a second hard ask immediately"],
  },
  {
    id: "framework_minber_zakat",
    profileId: "brand_minber_aksa",
    name: "Zakat",
    type: "ZAKAT",
    locale: "en",
    structure: ["Eligibility", "Intention", "Separated receipt", "Proof", "Donate"],
    sampleText: "Give zakat with clear intention, separated receipt handling, and field proof where available.",
    doList: ["Mention zakat handling", "Avoid fake scholar claims"],
    dontList: ["Do not invent eligibility claims", "Do not hide verification gaps"],
  },
  {
    id: "framework_minber_waqf",
    profileId: "brand_minber_aksa",
    name: "Waqf",
    type: "WAQF",
    locale: "en",
    structure: ["Lasting impact", "Dedication", "Certificate", "Updates", "Donate"],
    sampleText: "Dedicate an Al-Quds waqf share by name and receive a certificate after donation.",
    doList: ["Show certificate preview", "Make dedication clear"],
    dontList: ["Do not use heavy patterns over forms", "Do not overstate permanence without project detail"],
  },
  {
    id: "framework_minber_emergency",
    profileId: "brand_minber_aksa",
    name: "Emergency",
    type: "EMERGENCY",
    locale: "en",
    structure: ["Where", "What is needed", "How donation helps", "Proof/update", "CTA"],
    sampleText: "Help deliver urgent aid to Gaza through official Minber projects with receipt and impact updates.",
    doList: ["Name the place", "Keep urgency evidence-based"],
    dontList: ["Do not invent live stats", "Do not use unverified images"],
  },
  {
    id: "framework_goz_reactivation",
    profileId: "brand_gozbebekleri",
    name: "Donor reactivation",
    type: "DONOR_REACTIVATION",
    locale: "tr",
    structure: ["Warm recognition", "Relevant project", "Simple ask", "Opt-out respect"],
    sampleText: "Daha önceki desteğiniz için teşekkür ederiz. Dilerseniz bu ayki yardım çalışmasına güvenli bağışla katılabilirsiniz.",
    doList: ["Respect previous support", "Keep opt-out respectful"],
    dontList: ["Do not shame inactive donors", "Do not imply obligation"],
  },
  {
    id: "framework_minber_ramadan",
    profileId: "brand_minber_aksa",
    name: "Ramadan",
    type: "RAMADAN",
    locale: "en",
    structure: ["Blessed timing", "Project/fund", "Zakat/sadaqah clarity", "Receipt", "CTA"],
    sampleText: "Give this Ramadan through official Minber projects for Al-Quds, Al-Aqsa and Gaza.",
    doList: ["Support RTL/LTR", "Mention zakat when applicable"],
    dontList: ["Do not crowd the donation form"],
  },
  {
    id: "framework_goz_general",
    profileId: "brand_gozbebekleri",
    name: "General campaign",
    type: "GENERAL",
    locale: "tr",
    structure: ["Need", "Trust cue", "Amount/action", "Proof"],
    sampleText: "Bugün güvenli bağışla sahadaki çalışmaya destek olun. Makbuz ve güncelleme bağış sonrası paylaşılır.",
    doList: ["One primary CTA", "Clear receipt line"],
    dontList: ["Do not mix too many campaigns in one message"],
  },
];
